version: "4"
services:
  chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub

  firefox:
    image: selenium/node-firefox
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub

  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  cucumber-testcases-chrome:
    image: cucumbertestimage
    depends_on:
      - hub
    environment:
      - browser=Chrome
    volumes:
      - ./chromeexecutionreport:/home/seleniumbddcucumbertestframework/target

  cucumber-testcases-firefox:
    image: cucumbertestimage
    depends_on:
      - hub
    environment:
      - browser=Firefox
    volumes:
      - ./firfoxexecutionreport:/home/seleniumbddcucumbertestframework/target         